name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_AUTO_DELETE_MESSAGE_DURATION: ${{secrets.AUTO_DELETE_MESSAGE_DURATION}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_DOWNLOAD_DIR: ${{secrets.DOWNLOAD_DIR}}
          HD_DOWNLOAD_STATUS_UPDATE_INTERVAL: ${{secrets.DOWNLOAD_STATUS_UPDATE_INTERVAL}}
          HD_IS_TEAM_DRIVE: ${{secrets.IS_TEAM_DRIVE}}
          HD_GDRIVE_FOLDER_ID: ${{secrets.GDRIVE_FOLDER_ID}}
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH}}
          HD_UPSTREAM_REPO: ${{secrets.UPSTREAM_REPO}}
          HD_UPSTREAM_BRANCH: ${{secrets.UPSTREAM_BRANCH}}
          HD_INDEX_URL: ${{secrets.INDEX_URL}}
          HD_STOP_DUPLICATE: ${{secrets.STOP_DUPLICATE}}
          HD_VIEW_LINK: ${{secrets.VIEW_LINK}}
          HD_IGNORE_PENDING_REQUESTS: ${{secrets.IGNORE_PENDING_REQUESTS}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_UPTOBOX_TOKEN: ${{secrets.UPTOBOX_TOKEN}}
          HD_MEGA_API_KEY: ${{secrets.MEGA_API_KEY}}
          HD_MEGA_EMAIL_ID: ${{secrets.MEGA_EMAIL_ID}}
          HD_MEGA_PASSWORD: ${{secrets.MEGA_PASSWORD}}
          HD_BUTTON_FOUR_NAME: ${{secrets.BUTTON_FOUR_NAME}}
          HD_BUTTON_FOUR_URL: ${{secrets.BUTTON_FOUR_URL}}
          HD_BUTTON_FIVE_NAME: ${{secrets.BUTTON_FIVE_NAME}}
          HD_BUTTON_FIVE_URL: ${{secrets.BUTTON_FIVE_URL}}
